---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8000, host: 8000, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus:  13.10.0

platforms:
  - name: centos-6.8
    attributes:
      yum:
        base:
          baseurl: http://archive.kernel.org/centos-vault/6.8/os/x86_64/
        extras:
          baseurl: http://archive.kernel.org/centos-vault/6.8/extras/x86_64/
        updates:
          baseurl: http://archive.kernel.org/centos-vault/6.8/updates/x86_64/
  - name: centos-7.8
  
verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris::default]
      - recipe[pris_test::file_source]
      - recipe[pris_test::http_source]
      - recipe[pris_test::jdbc_source]
      - recipe[pris_test::merge_source]
      - recipe[pris_test::script_source]
      - recipe[pris_test::xls_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/file_source
        - path: test/integration/http_source
        - path: test/integration/jdbc_source
        - path: test/integration/merge_source
        - path: test/integration/script_source
        - path: test/integration/xls_source
  - name: file_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::file_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/file_source
  - name: http_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::http_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/http_source
  - name: jdbc_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::jdbc_source]
  - name: merge_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::merge_source]
  - name: script_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::script_source]
  - name: xls_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::xls_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xls_source
  - name: delete_xls_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::delete_xls_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/delete_xls_source
  - name: edit_script_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::edit_script_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/edit_script_source
  - name: create_if_missing_script_source
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[pris_java::default]
      - recipe[pris_test::create_if_missing_script_source]
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/create_if_missing_script_source
