---
driver:
  name: dokken
  network:
    - ["forwarded_port", {guest: 8000, host: 8000, auto_correct: true}]

transport:
  name: dokken

provisioner:
  name: dokken
  require_chef_omnibus:  13.10.0

platforms:
  - name: oraclelinux 9
    attributes:
      yum:
        base:
          baseurl: http://archive.kernel.org/centos-vault/6.8/os/x86_64/
        extras:
          baseurl: http://archive.kernel.org/centos-vault/6.8/extras/x86_64/
        updates:
          baseurl: http://archive.kernel.org/centos-vault/6.8/updates/x86_64/
  - name: oraclelinux 9
    attributes:
      pris:
        java_home: /usr/lib/jvm/java-11
  
verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/file_source
        - path: test/integration/http_source
        - path: test/integration/jdbc_source
        - path: test/integration/merge_source
        - path: test/integration/script_source
        - path: test/integration/xls_source
  - name: file_source
    provisioner:
      policyfile: test/policyfiles/file_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/file_source
  - name: http_source
    provisioner:
      policyfile: test/policyfiles/http_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/http_source
  - name: jdbc_source
    provisioner:
      policyfile: test/policyfiles/jdbc_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/jdbc_source
  - name: merge_source
    provisioner:
      policyfile: test/policyfiles/merge_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/merge_source
  - name: script_source
    provisioner:
      policyfile: test/policyfiles/script_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/script_source
  - name: xls_source
    provisioner:
      policyfile: test/policyfiles/xls_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xls_source
  - name: delete_xls_source
    provisioner:
      policyfile: test/policyfiles/delete_xls_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/delete_xls_source
  - name: edit_script_source
    provisioner:
      policyfile: test/policyfiles/edit_script_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/edit_script_source
  - name: create_if_missing_script_source
    provisioner:
      policyfile: test/policyfiles/create_if_missing_script_source.rb
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/create_if_missing_script_source
