---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[opennms-pris::default]
    attributes:
      java: 
        jdk_version: 7
