name 'pris'
maintainer 'David Schlenk'
maintainer_email 'dschlenk@convergeone.com'
license 'Apache-2.0'
description 'Installs/Configures opennms-pris'
version '2.0.0'
chef_version '>= 13.0'

supports 'centos', '>= 7.0'
supports 'oracle', '>= 7.0'
