version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: install cinc workstation
          command: curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -v 24
      - run:
          name: cinc
          command: cinc shell-init bash
      - run:
          name: bundler
          command: cinc exec bundle install
      - run:
          name: cookstyle
          command: cinc exec rake style
      - run:
          name: chefspec
          command: cinc exec rake unit
      - run:
          name: kitchen
          command: cinc exec rake integration
workflows:
  version: 2
  untagged-build:
    jobs:
      - test
