version: 2.1

jobs:
  test:  
    machine:
      image: ubuntu-2004:2023.07.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: install vagrant
          command: |
            TEMP_DEB="${mktemp)" &&
            wget -O "$TEMP_DEB" 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb' &&
            sudo dpkg -i "$TEMP_DEB"
            rm -f "$TEMP_DEB"
      - run:
          name: install chefdk
          command: |
            TEMP_DEB="$(mktemp)" &&
            wget -O "$TEMP_DEB" 'https://packages.chef.io/files/stable/chefdk/3.13.1/ubuntu/16.04/chefdk_3.13.1-1_amd64.deb' &&
            sudo dpkg -i "$TEMP_DEB"
            rm -f "$TEMP_DEB"
      - run:
          name: style
          command: chef exec rake style
      - run:
          name: unit
          command: chef exec rake unit
      - run:
          name: integration
          command: chef exec rake integration

workflows:
  version: 2
  test:
    jobs:
      - test
